### ISSUE TITLE
Getting This Error While Generating Video

### ISSUE THREAD

**Issue by RFedz007989** [light-and-ray/sd-webui-replacer#102]
Hi,

Hope you are doing good.
I am geting this error again & again while generating (Replacer Video). Pls check the below mentioned error.

(AttributeError: 'ControlNetUnit' object has no attribute 'copy')

Pls Assist where I am going/doing wrong.
Thank You

**Comment by RFedz007989** [comment]
I am using Forge not a1111 might this be the issue I don't know or should I use a1111.
Thank You

**Comment by RFedz007989** [comment]
I am using Forge not a1111 might this be the issue I don't know or should I use a1111.
Thank You.

**Comment by RFedz007989** [comment]
> Yes, you should install a1111. I tried to support Forge, but its author ignored my patches, abandoned the project, then broke everything, uses master branch as dev. Idk how to say, but he is strange 🤷🏻‍♂️

Sorry to hear Forge rejected your project. As you suggested I will download A1111.
Thanks

**Comment by RFedz007989** [comment]
As you suggested I downloaded A1111 & yes now It's working, but when came to video generation It gave me rror.
{ffmpeg exited with code 1}

**Comment by RFedz007989** [comment]
This is my console.

{[image2 @ 0000017637bfc6c0] Could find no file with path 'D:\ForgeWebUI\SD 2024\New folder\Videos\Replacer project - 1726524831\outputs\1726525222\result\%5d-3950909010.png' and index in the range 0-4
D:\ForgeWebUI\SD 2024\New folder\Videos\Replacer project - 1726524831\outputs\1726525222\result\%5d-3950909010.png: No such file or directory
*** Error completing request
*** Arguments: ('task(g5brcjxlpmpvqx0)', 'D:\\ForgeWebUI\\SD 2024\\New folder\\Videos\\Replacer project - 1726524831', 2, 36, 0, 12, 1, -1, 1, 16, False, 'None', 1, True, 'epicphotogasm_x-inpainting.safetensors [28875d1024]', 'None', '', '', 'colorful swimsuit', '', 'None', -1, 'DPM++ 2M SDE', 'Automatic', 20, 0.3, 35, 4, 1280, 'sam_hq_vit_h.pth', 'GroundingDINO_SwinT_OGC (694MB)', 5.5, 1, 90, 0, 512, 512, 0, False, False, 'epicphotogasm_x-inpainting.safetensors [28875d1024]', 'Random', True, 1, False, False, False, '-', -1, 0, False, True, True, False, 1, 0.5, 4, 0, 0.5, 2) {}
    Traceback (most recent call last):
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\video\generation.py", line 170, in videoGenerateUI
        save_video(resultPath, target_video_fps, originalVideo, saveVideoPath, gArgs.seed)
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_tools.py", line 63, in save_video
        runFFMPEG(
      File "D:\ForgeWebUI\SD 2024\New folder\setup\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_tools.py", line 20, in runFFMPEG
        raise Exception(f'ffmpeg exited with code {rc}. See console for details')
    Exception: ffmpeg exited with code 1. See console for details}

Can you find the exact cause of this error.

Actually I think this might be the reason for this error
([image2 @ 0000017637bfc6c0] Could find no file with path 'D:\ForgeWebUI\SD 2024\New folder\Videos\Replacer project - 1726524831\outputs\1726525222\result\%5d-3950909010.png' and index in the range 0-4
D:\ForgeWebUI\SD 2024\New folder\Videos\Replacer project - 1726524831\outputs\1726525222\result\%5d-3950909010.png: No such file or directory)

Thank You

**Comment by RFedz007989** [comment]
No actually I am using frame by frame & not animated one.
