### ISSUE TITLE
Problem with masking

### ISSUE THREAD

**Issue by mandubr** [light-and-ray/sd-webui-replacer#109]
I'm sorry but I'm newbie at Python, do anyone have any fix for this issue?

```
Start SAM Processing
Using local groundingdino., ?it/s]
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
C:\Users\mandu\sd.webui\webui\venv\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Downloading: "https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swint_ogc.pth" to C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\models/grounding-dino\groundingdino_swint_ogc.pth
    [Replacer]    Exception: HTTPSConnection.__init__() got an unexpected keyword argument 'verify'
*** ***
    Traceback (most recent call last):
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\generate.py", line 131, in generate
        processed, extraImages = generateSingle(image, gArgs, saveDir_, saveSuffix,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\generate.py", line 33, in generateSingle
        maskResult: MaskResult = createMask(image, gArgs)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 201, in createMask
        masksCreator = MasksCreator(gArgs.detectionPrompt, gArgs.avoidancePrompt, image, gArgs.samModel,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 80, in __init__
        self._createMasks()
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 102, in _createMasks
        masks, samLog = sam_predict(self.samModel, imageResized, [], [], True,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 200, in sam_predict
        boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
        dino_model = load_dino_model(dino_model_name, install_success)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 120, in load_dino_model
        checkpoint = torch.hub.load_state_dict_from_url(
      File "C:\Users\mandu\sd.webui\webui\venv\lib\site-packages\torch\hub.py", line 766, in load_state_dict_from_url
        download_url_to_file(url, cached_file, hash_prefix, progress=progress)
      File "C:\Users\mandu\sd.webui\webui\venv\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
        u = urlopen(req)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1317, in do_open
        h = http_class(host, timeout=req.timeout, **http_conn_args)
    TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'verify'

---
*** Error completing request
*** Arguments: ('task(ocut6nym8u5dz0s)', 'tab_single', 'background', '', 'waterfall', 'poor quality, low quality,  low res', <PIL.Image.Image image mode=RGBA size=1920x1080 at 0x23BC289D480>, None, True, '', '', True, False, 'None', -1, 'DPM++ 2M SDE', 'Automatic', 20, 0.3, 35, 4, 1280, 'sam_hq_vit_l.pth', 'GroundingDINO_SwinT_OGC (694MB)', 5.5, 1, 90, 0, 512, 512, 1, 1, 0, ['script'], False, False, 'epicphotogasm_z-inpainting.safetensors [d157850094]', 'Random', ['Draw mask'], None, True, ['Draw mask'], None, True, None, 1, False, False, False, '-', -1, 0, False, True, True, 'ESRGAN_4x', 4, 'Use same sampler', 'Use same scheduler', 0.35, 1, '', 1800, 'Lanczos', True, True, 5, '', '', 'Use same checkpoint', 90, 2, True, 'Same', 1.6, False, 1, 0.5, 4, 0, 0.5, 2) {}
    Traceback (most recent call last):
      File "C:\Users\mandu\sd.webui\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\mandu\sd.webui\webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "C:\Users\mandu\sd.webui\webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\ui\generate_ui.py", line 278, in generate_ui
        return generate_ui_(*args, **kwargs)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\ui\generate_ui.py", line 258, in generate_ui_
        processed, allExtraImages = generate(gArgs, saveDir, saveToSubdirs, extra_includes)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\generate.py", line 131, in generate
        processed, extraImages = generateSingle(image, gArgs, saveDir_, saveSuffix,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\generate.py", line 33, in generateSingle
        maskResult: MaskResult = createMask(image, gArgs)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 201, in createMask
        masksCreator = MasksCreator(gArgs.detectionPrompt, gArgs.avoidancePrompt, image, gArgs.samModel,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 80, in __init__
        self._createMasks()
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-replacer\replacer\mask_creator.py", line 102, in _createMasks
        masks, samLog = sam_predict(self.samModel, imageResized, [], [], True,
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 200, in sam_predict
        boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
        dino_model = load_dino_model(dino_model_name, install_success)
      File "C:\Users\mandu\sd.webui\webui\extensions\sd-webui-segment-anything\scripts\dino.py", line 120, in load_dino_model
        checkpoint = torch.hub.load_state_dict_from_url(
      File "C:\Users\mandu\sd.webui\webui\venv\lib\site-packages\torch\hub.py", line 766, in load_state_dict_from_url
        download_url_to_file(url, cached_file, hash_prefix, progress=progress)
      File "C:\Users\mandu\sd.webui\webui\venv\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
        u = urlopen(req)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "C:\Users\mandu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1317, in do_open
        h = http_class(host, timeout=req.timeout, **http_conn_args)
    TypeError: HTTPSConnection.__init__() got an unexpected keyword argument 'verify'
```

**Comment by mandubr** [comment]
Nevermind, it's fixed.

Somehow I got problems with "sam_hq_vit_l.pth", changed to the other available SAM and it worked.
