### ISSUE TITLE
tab replacer not show up 

### ISSUE THREAD

**Issue by Blackstylez83** [light-and-ray/sd-webui-replacer#12]
Hai, 
i already install sd web ui segment anything, then i install replacer, but when i restart the A1111 server this error show up and Replacer tab not show up,  any advice ?

*** Error loading script: replacer_main_ui.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 2, in <module>
        from modules import scripts, shared, sd_samplers, ui_toprow, ui, script_callbacks
    ImportError: cannot import name 'ui_toprow' from 'modules' (unknown location)

**Comment by Blackstylez83** [comment]
Thankss... it works after update :D
