### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by zachysaur** [light-and-ray/sd-webui-replacer#19]
[image2 @ 00000184b9a2b700] Could find no file with path 'C:\Users\ggrov\Downloads\out_1765400657\%5d-1765400657.jpg' and index in the range 0-4
C:\Users\ggrov\Downloads\out_1765400657\%5d-1765400657.jpg: No such file or directory
*** Error completing request
*** Arguments: ('task(8suv0abpbp9lbhs)', '', '', 'police uniform ', '', 3.0, None, None, '', '', False, 'C:\\Users\\ggrov\\Downloads\\1.mp4', 10, '', -1, 'DPM++ 2M SDE Karras', 20, 0.3, 35, 4, 1024, 'sam_hq_vit_l.pth', 'GroundingDINO_SwinB (938MB)', 5.5, 1, 20, 0, 512, 1, 512, 1, 0, False, []) {}
    Traceback (most recent call last):
      File "D:\Webui1111\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Webui1111\stable-diffusion-portable-main\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\generate.py", line 474, in generate_webui
        return generate(*args, **kwargs)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\generate.py", line 368, in generate
        save_video(output_batch_dir, fps_out, input_video, save_video_path, seed)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\video_tools.py", line 87, in save_video
        raise Exception(f'ffmpeg exited with code {rc}. See console for details')
    Exception: ffmpeg exited with code 1. See console for details

---

**Comment by zachysaur** [comment]
Dilation Amount:  39
Dilation Amount:  39
MasksCreator cached
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:40<00:00,  2.01s/it]
generate done, generating video██████████████████████████████████████████████████████| 580/580 [27:38<00:00,  2.02s/it]
D:\Webui1111\stable-diffusion-portable-main\venv\lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win64-v4.2.2.exe -framerate 10 -i C:\Users\ggrov\Documents\out_931916540\%5d-931916540.jpg -r 10 -i C:\Users\ggrov\Documents\roject.mp4 -map 0:v:0 -map 1:a:0? -c:v libx264 -c:a aac -vf fps=10 -profile:v main -pix_fmt yuv420p -shortest -y C:\Users\ggrov\Documents\out_931916540\output_roject.mp4_931916540.mp4
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[image2 @ 0000025b5152b700] Could find no file with path 'C:\Users\ggrov\Documents\out_931916540\%5d-931916540.jpg' and index in the range 0-4
C:\Users\ggrov\Documents\out_931916540\%5d-931916540.jpg: No such file or directory
*** Error completing request
*** Arguments: ('task(qvvgo8cwy6ypjt6)', '', '', 'police uniform ', '', 3.0, None, None, '', '', False, 'C:\\Users\\ggrov\\Documents\\roject.mp4', 10, '', -1, 'DPM++ 2M SDE Karras', 20, 0.3, 39, 4, 1024, 'sam_hq_vit_l.pth', 'GroundingDINO_SwinB (938MB)', 5.5, 1, 20, 0, 512, 1, 512, 1, 0, False, []) {}
    Traceback (most recent call last):
      File "D:\Webui1111\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Webui1111\stable-diffusion-portable-main\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\generate.py", line 474, in generate_webui
        return generate(*args, **kwargs)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\generate.py", line 368, in generate
        save_video(output_batch_dir, fps_out, input_video, save_video_path, seed)
      File "D:\Webui1111\stable-diffusion-portable-main\extensions\sd-webui-replacer\replacer\video_tools.py", line 87, in save_video
        raise Exception(f'ffmpeg exited with code {rc}. See console for details')
    Exception: ffmpeg exited with code 1. See console for details

---
