### ISSUE TITLE
No Replacer tab on screen, new issue: OutputPanel' object has no attribute 'html_info'

### ISSUE THREAD

**Issue by mqc40** [light-and-ray/sd-webui-replacer#21]
*** Error executing callback ui_tabs_callback for C:\SD_REPO\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\SD_REPO\stable-diffusion-webui\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
      File "C:\SD_REPO\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 310, in on_ui_tabs
        html_info = outputPanel.html_info
    AttributeError: 'OutputPanel' object has no attribute 'html_info'

---
Using SD1111 version: v1.7.0-331-gcb5b335a  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: d157850094

Thank you for support!

**Comment by mqc40** [comment]
Do you mean that my SD version is sdnext? 
In case yes, sorry but I was not aware... I just tought it was a SD update.
Thank you anyway for fast feedback!
