### ISSUE TITLE
Please add Webui Forge support too

### ISSUE THREAD

**Issue by mykeehu** [light-and-ray/sd-webui-replacer#35]
I tried to use the plugin on the [Webui Forge release](https://github.com/lllyasviel/stable-diffusion-webui-forge), but unfortunately I got an error that it cannot find the controlnet. The Forge edition comes with it factory installed, so you don't need to install it separately. If it helps, this is the error your extension is giving you now:

```
    [Replacer]    Exception: No module named 'internal_controlnet'
*** Error completing request
*** Arguments: ('task(vsvb9gnf7ck877g)', 'shirt', '', 'woman body', 'poor quality, low quality,  low res', 0.0, <PIL.Image.Image image mode=RGBA size=512x512 at 0x253AA655300>, None, True, '', '', True, False, '', '', 10, '', -1, 'DPM++ 2M SDE Karras', 20, 0.3, 35, 4, 1280, 'mobile_sam.pt', 'GroundingDINO_SwinT_OGC (694MB)', 5.5, 1, 40, 0, 512, 1, 512, 1, 0, ['script'], False, False, 'NSFW\\juggernaut_reborn.safetensors', 'Random', ['Draw mask'], None, True, ['Draw mask'], None, UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=(False,), batch_image_dir=('',), batch_input_gallery=([],), generated_image=(None,), mask_image=(None,), enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=(False,), batch_image_dir=('',), batch_input_gallery=([],), generated_image=(None,), mask_image=(None,), enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=(False,), batch_image_dir=('',), batch_input_gallery=([],), generated_image=(None,), mask_image=(None,), enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>), UiControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=(False,), batch_image_dir=('',), batch_input_gallery=([],), generated_image=(None,), mask_image=(None,), enabled=False, module='None', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>)) {}
    Traceback (most recent call last):
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\extensions\sd-webui-replacer\replacer\generate.py", line 561, in generate_webui
        return generate(*args, **kwargs)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\extensions\sd-webui-replacer\replacer\generate.py", line 409, in generate
        processed, extraImages = generateSingle(image, gArgs, saveDir, "", save_to_dirs,
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\extensions\sd-webui-replacer\replacer\generate.py", line 171, in generateSingle
        processed, scriptImages = inpaint(image, gArgs, savePath, saveSuffix, save_to_dirs,
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\extensions\sd-webui-replacer\replacer\generate.py", line 92, in inpaint
        replacer_scripts.enableInpaintModeForCN(gArgs.cn_args)
      File "I:\Stable-Diffusion-Automatic\stable-diffusion-webui-forge\webui\extensions\sd-webui-replacer\replacer\replacer_scripts.py", line 18, in enableInpaintModeForCN
        from internal_controlnet.external_code import get_all_units_from
    ModuleNotFoundError: No module named 'internal_controlnet'
```

**Comment by mykeehu** [comment]
Perfect working, I tested. Thank you!
