### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ema7569** [light-and-ray/sd-webui-replacer#5]
Start SAM Processing
Found GroundingDINO in pip. Verifying if dynamic library build success.
GroundingDINO dynamic library have been successfully built.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
Initializing SAM to cuda
    [Replacer]    Exception: ''
*** Error completing request
*** Arguments: ('background', 'waterfall', 'poor quality, low quality,  low res', 0, <PIL.Image.Image image mode=RGBA size=512x768 at 0x2353B2A3EE0>, None, '', '', True, '1x-FrankenMapGenerator-CX-Lite', -1, 'DPM++ 2M SDE Karras', 20, 0.3, 35, 4, 'FastSAM-x.pt', 'GroundingDINO_SwinT_OGC (694MB)', 5.5, 1, 20, 0, 512, 1, 768, 1) {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_generate.py", line 263, in generate
        generateSingle(image, gArgs, saveDir, "", save_to_dirs)
      File "F:\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_generate.py", line 116, in generateSingle
        masksCreator = MasksCreator(gArgs.detectionPrompt, image, gArgs.samModel,
      File "F:\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_mask_creator.py", line 45, in __init__
        self._createMasks()
      File "F:\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_mask_creator.py", line 53, in _createMasks
        masks, samLog = sam_predict(self.samModel, self.image, [], [], True,
      File "F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 204, in sam_predict        sam = init_sam_model(sam_model_name)
      File "F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 129, in init_sam_model
        sam_model_cache[sam_model_name] = load_sam_model(sam_model_name)
      File "F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 80, in load_sam_model
        sam = sam_model_registry[model_type](checkpoint=sam_checkpoint_path)
    KeyError: ''

**Comment by ema7569** [comment]
Seem not working with 'FastSAM-x.pt'

**Comment by ema7569** [comment]
It not throw bug with sam_hq_vit_h.pth but when attempted to replace a background with a waterfall it just replace near nothing
