### ISSUE TITLE
AttributeError: 'KDiffusionSampler' object has no attribute 'vec_cc'

### ISSUE THREAD

**Issue by ghkim89** [light-and-ray/sd-webui-replacer#61]
![111111](https://github.com/light-and-ray/sd-webui-replacer/assets/113520648/27ae5a36-1803-4b94-bb24-d91521eb3049)

AttributeError: 'KDiffusionSampler' object has no attribute 'vec_cc'

Can you tell me how to resolve this error?

**Comment by ghkim89** [comment]
This error occurs when all currently applied extensions have been removed.

AttributeError: 'KDiffusionSampler' object has no attribute 'diffcg_enable'


To create a public link, set `share=True` in `launch()`.
Startup time: 5.6s (list SD models: 0.1s, load scripts: 1.9s, scripts before_ui_callback: 0.1s, create ui: 0.6s, gradio launch: 2.2s, add APIs: 0.4s, app_started_callback: 0.1s)
.
Total progress:   0%|                                                                                                                                    | 0/20 [04:18<?, ?it/s]
Total progress:   0%|                                                                                                                                    | 0/20 [04:18<?, ?it/s]M
asksCreator restored from cache                                                                                                                          | 0/20 [00:00<?, ?it/s] 
  0%|                                                                                                                                                    | 0/20 [00:00<?, ?it/s]
    [Replacer]    Exception: 'KDiffusionSampler' object has no attribute 'diffcg_enable'
*** ***
    Traceback (most recent call last):
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\generate.py", line 140, in generate
        processed, extraImages = generateSingle(image, gArgs, saveDir_, saveSuffix,
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\generate.py", line 45, in generateSingle
        processed, scriptImages = inpaint(image, gArgs, savePath, saveSuffix, save_to_dirs,
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\inpaint.py", line 90, in inpaint
        processed = process_images(p)
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 981, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)   
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 1732, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_kdiffusion.py", line 172, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **e
xtra_params_kwargs))
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_kdiffusion.py", line 172, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **e
xtra_params_kwargs))
      File "h:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\pinokio\api\automatic1111.git\app\repositories\k-diffusion\k_diffusion\sampling.py", line 628, in sample_dpmpp_2m_sde
        callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-diffusion-cg\scripts\diffusion_cg.py", line 29, in center_callback
        if not self.diffcg_enable or getattr(self.p, "_ad_inner", False):
    AttributeError: 'KDiffusionSampler' object has no attribute 'diffcg_enable'

---
*** Error completing request
*** Arguments: ('task(vhgx3k4ovcwdzoa)', 'tab_single', 'dog', '', 'cat', '', <PIL.Image.Image image mode=RGBA size=1024x1024 at 0x155B87CA830>, None, True, '', '', True, False, 
'', '', 12, 'None', -1, 'DPM++ 2M SDE', 'Automatic', 20, 0.3, 35, 4, 1280, 'sam_vit_h_4b8939.pth', 'GroundingDINO_SwinT_OGC (694MB)', 5.5, 1, 40, 0, 512, 512, 1, 1, 0, ['script'
], False, False, 'sd_xl_base_1.0.safetensors [31e35c80fc]', 'Random', ['Draw mask'], None, True, ['Draw mask'], None, True, None, '', 2, False, False, [], False, 'video_mode_ani
matediff', 36, 0, 12, 1, -1, 1, 16, False, 'None', 1, True, 'awpainting_v13.safetensors [5a44dad2e0]', 'None', 'ESRGAN_4x', 4, 'Use same sampler', 'Use same scheduler', 0.35, 1,
 '', 1800, 'Lanczos', True, True, 5, '', '', 'Use same checkpoint', 250, 2, True, 'Same', False, 1, 0.5, 4, 0, 0.5, 2) {}
    Traceback (most recent call last):
      File "H:\pinokio\api\automatic1111.git\app\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "H:\pinokio\api\automatic1111.git\app\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\ui\generate_ui.py", line 301, in generate_ui
        processed, allExtraImages = generate(gArgs, saveDir, saveToSubdirs, useSaveFormatForVideo, extra_includes)
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\generate.py", line 140, in generate
        processed, extraImages = generateSingle(image, gArgs, saveDir_, saveSuffix,
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\generate.py", line 45, in generateSingle
        processed, scriptImages = inpaint(image, gArgs, savePath, saveSuffix, save_to_dirs,
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-replacer\replacer\inpaint.py", line 90, in inpaint
        processed = process_images(p)
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 981, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)   
      File "H:\pinokio\api\automatic1111.git\app\modules\processing.py", line 1732, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_kdiffusion.py", line 172, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **e
xtra_params_kwargs))
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "H:\pinokio\api\automatic1111.git\app\modules\sd_samplers_kdiffusion.py", line 172, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **e
xtra_params_kwargs))
      File "h:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\pinokio\api\automatic1111.git\app\repositories\k-diffusion\k_diffusion\sampling.py", line 628, in sample_dpmpp_2m_sde
        callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
      File "H:\pinokio\api\automatic1111.git\app\extensions\sd-webui-diffusion-cg\scripts\diffusion_cg.py", line 29, in center_callback
        if not self.diffcg_enable or getattr(self.p, "_ad_inner", False):
    AttributeError: 'KDiffusionSampler' object has no attribute 'diffcg_enable'

---

**Comment by ghkim89** [comment]
I removed the venv folder and reinstalled it, but I got the same error.
