### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

### ISSUE THREAD

**Issue by Tbrock8905** [light-and-ray/sd-webui-replacer#62]
Hi,

Getting this error. Automatic1111 is up to date v 1.9

*** Error executing callback ui_tabs_callback for C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 17, in on_ui_tabs
        tab = replacer_tab_ui.replacerMainUI.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

**Comment by Tbrock8905** [comment]
venv "C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.0
Commit hash: adadb4e3c7382bf3e4f7519126cd6c70f4f8557b
Installing requirements
ReActor preheating... Device: CUDA
bin C:\Users\xxxx\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: f352739bb5fee3644b3375ec7785a1b263127b68
Checking xformers...
Installing xformers
Detected torch version 2.0.1+cu118
Installing xformers from PyPI
Error occurred:

Usage:

  C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...

  C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...

  C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] [-e] <vcs project url> ...

  C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] [-e] <local project path> ...

  C:\Users\xxxx\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] <archive url/path> ...



no such option: --index-url https://download.pytorch.org/whl/cu118


Checking bitsandbytes...
Checking bitsandbytes (Windows)
Virtual environment path: C:\Users\xxxx\stable-diffusion-webui\venv
Checking for C:\Users\xxxx\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Checking Dreambooth requirements...
[Dreambooth] accelerate v0.21.0 is already installed.
[Dreambooth] dadaptation v3.2 is already installed.
[Dreambooth] diffusers v0.23.1 is already installed.
[Dreambooth] discord-webhook v1.3.0 is already installed.
[Dreambooth] fastapi is already installed.
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.43

[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
[Dreambooth] Pillow is already installed.
[Dreambooth] tqdm is already installed.
[Dreambooth] tomesd v0.1.2 is already installed.
[Dreambooth] tensorboard v2.13.0 is already installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.25.0 installed.
[+] bitsandbytes version 0.41.2.post2 installed.
[!] xformers version 0.0.20 installed.
Launching Web UI with arguments: --xformers --medvram
bin C:\Users\xxxx\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
2024-04-18 21:19:46.430940: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\xxxx\stable-diffusion-webui\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.20.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 23.12.0, num models: 9
ControlNet preprocessor location: C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-18 21:19:56,904 - ControlNet - INFO - ControlNet v1.1.426
2024-04-18 21:19:57,185 - ControlNet - INFO - ControlNet v1.1.426
21:19:59 - ReActor - STATUS - Running v0.6.0-a4
21:19:59 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [d157850094] from C:\Users\xxxx\stable-diffusion-webui\models\Stable-diffusion\epicphotogasm_z-inpainting.safetensors
*** Error executing callback before_ui for C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\modules\script_callbacks.py", line 397, in before_ui_callback
        c.callback()
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_tab_ui.py", line 525, in initMainUI
        replacer_extensions.initAllScripts()
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\extensions\replacer_extensions.py", line 16, in initAllScripts
        controlnet.initCNScript()
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\extensions\controlnet.py", line 47, in initCNScript
        initCNContext()
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\extensions\controlnet.py", line 67, in initCNContext
        oldCNContext = copy.copy(ControlNetUiGroup.a1111_context)
    AttributeError: type object 'ControlNetUiGroup' has no attribute 'a1111_context'

---
2024-04-18 21:20:02,113 - AnimateDiff - INFO - Injecting LCM to UI.
Civitai Helper: Set Proxy:
Creating model from config: C:\Users\xxxx\stable-diffusion-webui\configs\v1-inpainting-inference.yaml
*** Error calling: C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_script.py/ui
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\modules\scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_script.py", line 57, in ui
        comp = replacer_tab_ui.replacerMainUI.components
    AttributeError: 'NoneType' object has no attribute 'components'

---
2024-04-18 21:20:02,389 - AnimateDiff - INFO - Hacking i2i-batch.
*** Error calling: C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_script.py/ui
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\modules\scripts.py", line 528, in wrap_call
        return func(*args, **kwargs)
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_script.py", line 57, in ui
        comp = replacer_tab_ui.replacerMainUI.components
    AttributeError: 'NoneType' object has no attribute 'components'

---
Applying attention optimization: xformers... done.
Model loaded in 3.9s (load weights from disk: 0.2s, create model: 1.0s, apply weights to model: 2.1s, calculate empty prompt: 0.5s).
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\xxxx/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\xxxx/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\xxxx/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\xxxx/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\xxxx/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
*** Error executing callback ui_tabs_callback for C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 17, in on_ui_tabs
        tab = replacer_tab_ui.replacerMainUI.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

---
Running on local URL: 

To create a public link, set `share=True` in `launch()`.
*** [Replacer] error while creating dedicated page: 'NoneType' object has no attribute 'getReplacerTabUI'
    Traceback (most recent call last):
      File "C:\Users\xxxx\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 37, in mountDedicatedPage
        tab = replacer_tab_ui.replacerMainUI_dedicated.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

---
Startup time: 63.2s (prepare environment: 36.7s, import torch: 3.0s, import gradio: 0.9s, setup paths: 6.5s, initialize shared: 0.2s, other imports: 0.8s, list SD models: 0.1s, load scripts: 8.7s, create ui: 5.7s, gradio launch: 0.4s).
Advanced elements visible: False

**Comment by Tbrock8905** [comment]
All good - updated my controlnet. My bad
