### ISSUE TITLE
Error from installing

### ISSUE THREAD

**Issue by elixirbeats** [light-and-ray/sd-webui-replacer#7]
Hello, after installing this I got this stacktrace on restarting the UI. 

*** Error loading script: replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Shared\repos\stable_diffusion\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Shared\repos\stable_diffusion\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Shared\repos\stable_diffusion\webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 4, in <module>
        from modules import scripts, shared, sd_samplers, ui_toprow, ui
    ImportError: cannot import name 'ui_toprow' from 'modules' (unknown location)

**Comment by elixirbeats** [comment]
Ah , i should have waited a few more minutes.. turns out my web ui was behind some commits! WOrking now, sorry

**Comment by MrBaralgin** [comment]
I have the exact same problem

**Comment by elixirbeats** [comment]
> I have the exact same problem

add "git pull" in your webstart bat file, after the commandline args, then it will update before each launch. Fixed it for me
