### ISSUE TITLE
The problem of the image being black after the clothes are redrawn has always existed. What caused this,

### ISSUE THREAD

**Issue by zhangjinyan888** [light-and-ray/sd-webui-replacer#73]
The problem of the image being black after the clothes are redrawn has always existed. What caused this,
![QQ截图20240515193805](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/ebe30d71-b551-41f6-9c29-db8b45d934e7)
![258](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/7a28a7ca-1efb-47d6-9f04-9a855ee9a67e)

[

https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/7177d1ce-61a3-4345-87f8-b6ef29a541eb

](url)

**Comment by zhangjinyan888** [comment]
Not single image mode, single image is normal, and multiple images are also normal. I am using video, but the video is not normal

**Comment by zhangjinyan888** [comment]
![1](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/57597064-4a37-4bfa-951f-81fcbd34856d)
![2](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/51cc9696-9073-4349-bdff-b9870b4f60ea)
![3](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/c889a999-c145-494e-8395-da22bc058034)
![4](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/35719f5a-dcab-4dcc-96a2-fbeedafbe5d3)
![5](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/ad000577-9238-47ae-9446-3c320a9e5580)
![6](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/ba7afec8-155d-478b-9d15-c93d50a49bdf)

**Comment by zhangjinyan888** [comment]
![8](https://github.com/light-and-ray/sd-webui-replacer/assets/22515039/7172c999-0c41-40ef-b2ee-968c8d6e1416)

**Comment by zhangjinyan888** [comment]
*** Error running before_process_batch: F:\ai\sd-webui-aki-v4.7\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\ai\sd-webui-aki-v4.7\modules\scripts.py", line 833, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "F:\ai\sd-webui-aki-v4.7\extensions\sd-webui-animatediff\scripts\animatediff.py", line 79, in before_process_batch
        AnimateDiffI2VLatent().randomize(p, params)
      File "F:\ai\sd-webui-aki-v4.7\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 84, in randomize
        p.init_latent = p.init_latent * init_alpha + p.rng.next() * (1 - init_alpha)
    RuntimeError: The size of tensor a (12) must match the size of tensor b (5) at non-singleton dimension 0

---

**Comment by zhangjinyan888** [comment]
After turning off semi precision optimization, it went back to normal
