### ISSUE TITLE
Replacer tab not appearing after update

### ISSUE THREAD

**Issue by explorerotter** [light-and-ray/sd-webui-replacer#78]
Does anyone have a fix for this issue?
Already tried the solutions on #16.

venv "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3-amd-13-g517aaaff
Commit hash: 517aaaff2bb1a512057d88b0284193b9f23c0b47
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-directml --opt-sub-quad-attention --no-half --disable-nan-check --autolaunch --medvram --opt-split-attention-v1 --api --precision full --upcast-sampling
ONNX: version=1.18.0 provider=DmlExecutionProvider, available=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
You are running torch 2.0.0+cpu.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
ControlNet preprocessor location: C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2024-05-23 14:26:49,933 - ControlNet - INFO - ControlNet v1.1.449
14:26:50 - ReActor - STATUS - Running v0.7.0-b7 on Device: CPU
Loading weights [93f7411be9] from C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\models\Stable-diffusion\realcartoon3d_v15.safetensors
*** Error executing callback before_ui for C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\modules\script_callbacks.py", line 397, in before_ui_callback
        c.callback()
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\replacer\ui\replacer_tab_ui.py", line 534, in initMainUI
        lenBefore = len(infotext_utils.registered_param_bindings)
    NameError: name 'infotext_utils' is not defined

---
[Replacer] Segment Anything accordion has been hidden
2024-05-23 14:26:51,132 - ControlNet - INFO - ControlNet UI callback registered.
[Replacer] Segment Anything accordion has been hidden
*** Error executing callback ui_tabs_callback for C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 16, in on_ui_tabs
        replacer_tab_ui.reinitMainUIAfterUICreated()
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\replacer\ui\replacer_tab_ui.py", line 547, in reinitMainUIAfterUICreated
        infotext_utils.registered_param_bindings += registered_param_bindings_main_ui
    NameError: name 'infotext_utils' is not defined

---
Creating model from config: C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Replacer] Segment Anything accordion has been hidden
[Replacer] Segment Anything accordion has been hidden
[Replacer] Segment Anything accordion has been hidden
[Replacer] Segment Anything accordion has been hidden
*** [Replacer] error while creating dedicated page: 'NoneType' object has no attribute 'getReplacerTabUI'
    Traceback (most recent call last):
      File "C:\Users\Victor\Desktop\Stable Diffusion\stable-diffusion-webui-directml\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 37, in mountDedicatedPage
        tab = replacer_tab_ui.replacerMainUI_dedicated.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

---
Startup time: 12.8s (prepare environment: 11.8s, initialize shared: 1.8s, load scripts: 2.5s, create ui: 0.4s, gradio launch: 0.5s, add APIs: 0.5s).
Applying attention optimization: sub-quadratic... done.
Model loaded in 4.9s (load weights from disk: 0.5s, load config: 0.2s, create model: 0.5s, apply weights to model: 2.0s, apply float(): 1.1s, calculate empty prompt: 0.5s).

**Comment by explorerotter** [comment]
It worked!
Thank you very much for the help for the help.
