### ISSUE TITLE
Replacer Tab do not show up, with error message

### ISSUE THREAD

**Issue by Cooly75** [light-and-ray/sd-webui-replacer#8]
Python 3.10.6
Win10 64

installed over extension tab

Error message as follow

*** Error executing callback ui_tabs_callback for P:\AI\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "X:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "X:\AI\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 152, in on_ui_tabs
        from scripts.sam import sam_model_list, refresh_sam_models
    ModuleNotFoundError: No module named 'scripts.sam'

**Comment by Cooly75** [comment]
Error found, permission on folder "...\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\models"  was restricted (dunno why, never dit a change to it), after allow full acces by main user manuel, all worked just fine.

This Issue report can be closed

**Comment by Cooly75** [comment]
> You need to install `sd-webui-segment-anything`, not `sd-webui-inpaint-anything`

its what i did but the models folder got restricted, by windowsdefender, and i still have no idea why.

**Comment by Cooly75** [comment]
in case someone else with win10 got the same issue, to put exeption on the folder and edit manuel permission solve that one.

By the way it is a stupid windumb issue, and it just came into my mind to check it after i remember it happen once with faceswap. it token me a while to fix that. lmao
