### ISSUE TITLE
    ImportError: cannot import name 'infotext_utils' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by OrloDavid** [light-and-ray/sd-webui-replacer#82]
Can't seem to get rid of this error no matter what I do or install. 

---
*** Error loading script: replacer_script.py
    Traceback (most recent call last):
      File "C:\Git\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Git\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Git\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_script.py", line 6, in <module>
        from replacer.ui import replacer_tab_ui
      File "C:\Git\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_tab_ui.py", line 2, in <module>
        from modules import shared, ui_settings, errors, infotext_utils
    ImportError: cannot import name 'infotext_utils' from 'modules' (unknown location)

**Comment by cocoph** [comment]
update webui to the lastest version by cmd > git pull

**Comment by OrloDavid** [comment]
SD-Webui? I have the Openvino version, maybe its behind.... 

https://github.com/openvinotoolkit/stable-diffusion-webui/tree/master
This branch is [132 commits ahead of](https://github.com/openvinotoolkit/stable-diffusion-webui/compare/AUTOMATIC1111%3Astable-diffusion-webui%3Amaster...master), [1398 commits behind](https://github.com/openvinotoolkit/stable-diffusion-webui/compare/master...AUTOMATIC1111%3Astable-diffusion-webui%3Amaster) AUTOMATIC1111/stable-diffusion-webui:master.

Last updates were something like 10 months ago, maybe I should fork it and roll the changes in. :(

**Comment by OrloDavid** [comment]
version: [v1.6.0-132-ge5a634da]


Sorry, it took a minute to even get it working again with Openvino. God forbid, I tried to use a completely different program which also used Openvino, OpenCV CL? One of those, ONNX, etc, then SD Wed wouldn't load and it took uninstalling all Python, removing the Git directories and literally starting from scratch and yes, I tried everything in-between which is why it took so long to respond. 

I so much hate Python's dependency / versioning / incompatibility (Is that a Python programming rule? Every version change, even minor, needs to completely break everything with 0 backwards compatibility. Like it's on a giant whiteboard for everyone who writes anything in Python? I assume it must be, because so many requirement files say only 1 specific version of something will work) and the Virtual Environment Implementation is a not how actual VE's, where the concept is modeled from, actually work, and that's my professional opinion on the VE's, the rest is just me being pissy due to the temperamental nature of these environments, I'm afraid to sneeze sometimes.
